### ISSUE TITLE
Test is failing

### ISSUE THREAD

**Issue by coder123456** [gwenn/sqlite-jna#2]
Failed tests: 
  SqliteDatabaseMetadataTest.testGetColumns:346 arrays first differed at element [8]; expected:<...aster|rootpage|4|INT[EGER]|10|null|10|10|1|nul...> but was:<...aster|rootpage|4|INT[]|10|null|10|10|1|nul...>

**Comment by gwenn** [comment]
Thanks!
All is ok in Travis CI and AppVeyor.
I guess the error is related to the [jlemon](https://github.com/gwenn/sqlite-jna/blob/master/pom.xml#L55) dependency.
I will check...

**Comment by gwenn** [comment]
Ok,
The test depends on the SQLite version.
`sqlite_master` is a table generated by SQLite.
```sh
SQLite version 3.19.3 2017-06-27 16:48:08
sqlite> pragma table_info('sqlite_master');
0|type|text|0||0
1|name|text|0||0
2|tbl_name|text|0||0
3|rootpage|integer|0||0
4|sql|text|0||0
```
vs
```sh
SQLite version 3.21.0 2017-10-24 18:55:49
sqlite> pragma table_info('sqlite_master');
0|type|text|0||0
1|name|text|0||0
2|tbl_name|text|0||0
3|rootpage|int|0||0
4|sql|text|0||0
```
