### ISSUE TITLE
BusyHandler is not a supported argument type

### ISSUE THREAD

**Issue by tranmanh90** [gwenn/sqlite-jna#6]
I am using sqlite3.dll 64bit version 3.31.1 and facing an error when creating a connection:
#Code
public class Test extends ScalarCallback {

    protected void func(SQLite.SQLite3Context pCtx, SQLite.SQLite3Values args) {
        int x=args.getInt(0);
        pCtx.setResultInt(x+1);
    }

    public static void main(String[] args) throws Exception {
        int flags = OpenFlags.SQLITE_OPEN_READWRITE | OpenFlags.SQLITE_OPEN_CREATE;
        Conn c = Conn.open("test.sqlite",flags,null);
        c.createScalarFunction("add_one",1, FunctionFlags.SQLITE_UTF8,new Test());
        String sql="SELECT add_one(1)";
        Stmt s=c.prepare(sql,false);
        if (s.step(1)) {
            System.out.println(s.getColumnInt(0));
        }
    }
}

#Error
Caused by: java.lang.IllegalArgumentException: class org.sqlite.BusyHandler is not a supported argument type (in method sqlite3_busy_handler in class org.sqlite.SQLite)
	at com.sun.jna.Native.register(Native.java:1727)
	at com.sun.jna.Native.register(Native.java:1370)
	at org.sqlite.SQLite.<clinit>(SQLite.java:31)
	... 2 more

Please help me resolve it
Many thanks

**Comment by gwenn** [comment]
Could you please provide a complete example or the full stacktrace ?

> at org.sqlite.SQLite.(SQLite.java:31)

https://github.com/gwenn/sqlite-jna/blob/master/src/main/java/org/sqlite/SQLite.java#L31
is where JNA is loading the DLL.
I guess your DLL is missing some features/declarations.

**Comment by tranmanh90** [comment]
I resolved it, because I used dependency
**<dependency>
     <groupId>org.xerial</groupId>
     <artifactId>sqlite-jdbc</artifactId>
     <version>3.30.1</version>
</dependency>**
It has a same **org.sqlite.BusyHandler** so maybe it confused.

But now I don't know how to use UpdateHook to listener event from database, Please give me an example
Thanks.

**Comment by gwenn** [comment]
https://github.com/gwenn/sqlite-jna/blob/master/src/test/java/org/sqlite/ConnTest.java#L326

**Comment by tranmanh90** [comment]
If i insert from command line or other sources, UpdateHook is still working or not ?

**Comment by gwenn** [comment]
http://sqlite.1065341.n5.nabble.com/Scope-of-sqlite3-update-hook-td92698.html
> No, only the connection it's registered with.

**Comment by tranmanh90** [comment]
> http://sqlite.1065341.n5.nabble.com/Scope-of-sqlite3-update-hook-td92698.html
> 
> > No, only the connection it's registered with.

Thanks for your support !!!
